stages:
  - test
  - build

backend:test:
  stage: test
  script:
    - cd backend && npm ci && npx prisma generate && npm run test:cov
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: backend/coverage/cobertura-coverage.xml
    paths:
      - backend/coverage/
    expire_in: 1 week

backend:build:
  stage: build
  script:
    - cd backend && npm ci && npx prisma generate && npm run build
  only:
    - main