sonar.projectKey=dmytro-balan-05_nexus-aid
sonar.organization=dmytro-balan-05
sonar.projectName=NexusAid
sonar.sources=backend/src,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/coverage/**,**/prisma/migrations/**
sonar.coverage.exclusions=**/campaigns/**,**/chat/**,**/donations/**,**/gamification/**,**/users/**,**/verification/**,**/auth/auth.controller.ts,**/auth/auth.module.ts,**/auth/dto/**,**/auth/guards/**,**/auth/strategies/**,**/main.ts,**/*.module.ts
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.qualitygate.wait=true