sonar.projectKey=dmytro-balan-05_nexus-aid
sonar.organization=dmytro-balan-05
sonar.projectName=NexusAid
sonar.sources=backend/src,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/coverage/**,**/prisma/migrations/**
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info